Preserve data
initseis/oop-school-library pull request #6
Opened 2021-10-12 21:27 UTC by sevinchek

In this branch @bimbolabuari and I:

- Stored the people data in JSON files
- Stored the books data in JSON files
- Stored the rentals data in JSON files
- Load data from files on start up
- Handle the case when one or more files are missing

2021-10-12 22:07 UTC, DeliceLydia requested changes
## Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._



### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-12 22:07 UTC, DeliceLydia commented on list_people.rb
> +      end
- [ ] Inside your `json` file I suggest that you add `json.class` like if is `people.json` file you can outputs:
`{"json_class":"Student","name":"Sam","age":"14","parent_permission":true}`
`{"json_class":"Teacher","name":"Fox","age":"56","parent_permission":true,"specialization":"Starships"}`

2021-10-12 22:07 UTC, DeliceLydia commented on list_books.rb
> +      puts "Title: #{b['title']}, Author: #{b['author']}"
- [ ] Please add a `json_class`

2021-10-12 22:07 UTC, DeliceLydia commented on create_rental.rb
> +        puts "#{index}) [Student] Name: #{p['name']}, ID: #{p['id']}, Age: #{p['age']}"
- [ ] Kindly add `json_class`

2021-10-13 00:13 UTC, oxenprogrammer approved these changes
```markdown
Hi @sevinchek  and @bimbolabuari, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-10-13 15:26 UTC, merged